# Generated by Django 3.2.3 on 2021-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Booking',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Check_in', models.CharField(max_length=255)),
                ('Check_out', models.CharField(max_length=255)),
                ('ADULT', models.CharField(max_length=255)),
                ('CHILDREN', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Nid_No', models.CharField(max_length=255)),
                ('Img', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Online_Booking_table',
            },
        ),
    ]
