# Generated by Django 3.2.3 on 2021-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_offline_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Employee',
            fields=[
                ('Employee_Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Mobile_Number', models.IntegerField()),
                ('Joining_Date', models.CharField(max_length=255)),
                ('Dateof_Birth', models.CharField(max_length=255)),
                ('Departments', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Blood_Group', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('Personal_Identity', models.CharField(max_length=255)),
                ('Guardian', models.CharField(max_length=255)),
                ('Guardian_Number', models.IntegerField()),
                ('Upload_Image', models.ImageField(upload_to='')),
                ('Address', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Add_Employees',
            },
        ),
    ]
