# Generated by Django 3.2.3 on 2021-07-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0006_add_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Salarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=255)),
                ('Mobile_Number', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=500)),
                ('Departments', models.CharField(max_length=255)),
                ('Salary', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Employee_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.add_employee')),
            ],
            options={
                'db_table': 'Add_Employee_salarys',
            },
        ),
    ]
